name: build and Deploy
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: npm dependencies
        run: npm ci
      - name: linting
        run: npm run lint
      - name: test
        run: npm run test
      - name: build
        run: npm run build

  deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: chekout
        uses: actions/checkout@v4
      - name: deploy
        run: echo "deploy files"