name: First workflow
on: workflow_dispatch
jobs:
   first-job:
     runs-on: ubuntu-latest
     steps:
       - name: Print greeting
         run: echo "hllo world"
       - name: Print Goodbue
         run: eho "good bye"
